# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

## Base settings ##
# url:  #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /
title: 刘凯的博客
description: > #this means to ignore newlines until "nav_lists:"
  刘凯的博客

nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html

paths:
  base: /
  home: /
  all:  /all.html
#  rss:  /feed.xml
#  CV: /CV/index.html

## GitHub repository (if the site is hosted by GitHub) ##
# repository:  #e.g. someone/someone.github.io
# repository_tree:  #e.g. master

## Language & timezone ##
lang: zh #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Asia/Shanghai #see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## Author & social ##
author:
  name: 刘凯
  email: kevenliu3@163.com #your Email address e.g. someone@site.com
  # facebook:  #your Facebook username
  # twitter:  #your Twitter username
  github:  kevenliu3
  # googleplus:  #your Google+ username
  # weibo:  gemmatiandi #your Weibo username
  # douban:  119266767 #your Douban username
  # linkedin:  #your Linkedin username

## Comment system (Disqus) ##
#disqus:
  #shortname: https-zh-mingemma-github-io-1-1

## Comment system (gitalk) ##
# please refer to https://github.com/gitalk/gitalk for more info.
# gitalk:
#  clientID:  xxx
#  clientSecret:  xxx
#  repository:  xxx
#  owner:  xxx
#  admin: xxx
    # 
## Google Analytics ##
# ga_tracking_id:  UA-115761164-1

## Reading quantity (LeanCloud) ##
# leancloud:
#   app_id:  BUD2nLLKnqggmwJT8BirBVSj-gzGzoHsz
#   app_key:  XYr8j6oSVRzigN9lBRKbhCov
#   app_class:  qWNmxGXm9aT1AyyR541s2rXh

# mathjax: true

## Paginate ##
paginate: 5
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: text # text | html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## Plugins ##
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"

## Development ##
isdebug: false

port : 4040
